// Ignore Spelling: Dox Mvc

using CompanyMvc.Dox.PL.ViewModels.Auth;
using System.Net;
using System.Net.Mail;

namespace CompanyMvc.Dox.PL.HelperLogic
{
	public static class EmailSettings
	{

		public static void SendEmail(EmailSending emailSending)
		{
			//Mail Server Ex: gmail.com,outlook.com,....
			//SMTP server mail Transfer Protocol
			var Client=new SmtpClient("smtp.gmail.com",587);
			Client.EnableSsl = true;//to encrypt email
			Client.Credentials = new NetworkCredential("hazemfady123@gmail.com","password not password this email but password generated by using Google");//hazemfady123@gmail.com this email that send to recievers
            Client.Send("hazemfady123@gmail.com", emailSending.To, emailSending.Subject, emailSending.Body);


		}
	}
}
